name: "buildEntities"
replicaCount: 1

images:
  PullSecrets: 
    name: kartingreg
  repository: genesisproject.azurecr.io/build-entity
  tag: "latest"

service:
  type: ClusterIP
  ports:
  - name: http
    port: 3000

# volume:
#   - name: buildEntities-volume
#     mountPath: 
#     secretName: azure-secret 
#     shareName: system-genesis/ 
#     type: azurefile 

config:
  configmaps: 
    name: buildEntities
